config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "reviews#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get "reviews", to: "reviews#index"
  post "reviews", to: "reviews#create"
  delete "reviews", to: "reviews#delete"
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :vote, class_name: 'Review'
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :favorites
    has_many :likes, through: :favorites, source: :vote
    
    def favorite(review)
      self.favorites.find_or_create_by(vote_id: review.vote_id)
    end
  
    def unfavorite(review)
      favorite = self.favorites.find_by(vote_id: review.vote_id)
      favorite.destroy if favorite
    end
  
    def favorite?(review)
      self.likes.include?(vote_id: review)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  include SessionsHelper
    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  require 'net/http'
  require 'json'
  require 'uri'
  
  API_BASE_URL='https://api.gnavi.co.jp/PhotoSearchAPI/v3/'
   
  def index
    keyword = params[:search]
    keyword ||= "美味しい"
    
    area = params[:area]
    
    param = {
      "keyid"         => "2591a7e3ba2c49fa50cf56339ec3441e",
      "comment"       => URI.encode(keyword),
      "hit_per_page"  => 50,
      "sort"          => 1
    }
    
    if area
      param["area"] = URI.encode(area)
    end
  
    uri = URI(API_BASE_URL + '?' + param.map{|k,v| "#{k}=#{v}"}.join('&'))
  
    response_json = Net::HTTP.get(uri)
  
    @response_data = JSON.parse(response_json)
    
    @review = Review.new
  end
    
  def create
    review = Review.find_by(vote_id: params[:vote_id])
    
    #レビューを保存、お気に入りにする処理
    if review
      current_user.favorite(review)
    else
      @review = Review.create(vote_id: params[:vote_id],image_url: params[:image_url],menu_name: params[:menu_name],shop_url: params[:shop_url],update_date: params[:update_date],shop_name: params[:shop_name],comment: params[:comment])
      @review.save
      current_user.favorite(@review)
    end
    
    flash[:success] = 'お気に入りに追加しました'
    redirect_back(fallback_location: root_path)
  end
    
  def delete
    #お気に入りを解除する処理
    review = Review.find_by(vote_id: params[:vote_id])
    current_user.unfavorite(review)
     
    flash[:success] = 'お気に入りを解除しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_user_logged_in, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def show
    #お気に入りにしたレビューを表示する処理
    @user = User.find(params[:id])
    @likes = @user.likes
    @review = Review.new
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorites_button.html.erb
<% if logged_in? %>
  <% unless current_user.likes.find_by(vote_id: review_data["vote_id"])%>
    <%= form_with model: review, local: true do |f| %>
      <%= hidden_field_tag :shop_url, review_data["shop_url"] %>
      <%= hidden_field_tag :shop_name, review_data["shop_name"] %>
      <%= hidden_field_tag :menu_name, review_data["menu_name"] %>
      <%= hidden_field_tag :image_url, review_data["image_url"]["url_320"] %>
      <%= hidden_field_tag :comment, review_data["comment"] %>
      <%= hidden_field_tag :update_date, review_data["update_date"] %>
      <%= hidden_field_tag :vote_id, review_data["vote_id"] %>
      <%= f.submit 'お気に入り', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% else %>
    <%= form_with model: review, local: true, method: :delete do |f| %>
      <%= hidden_field_tag :vote_id, review_data["vote_id"] %>
      <%= f.submit 'お気に入り解除', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4 sticky-top">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">ReviewList</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My Favolite', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'アカウント登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ReviewList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>
</html>

app/views/reviews/index.html.erb
<div class="d-flex align-items-center justify-content-center mb-3">
  <%= form_with url: "/", method: :get, local: true do |f| %>
    <%= f.text_field :search, placeholder: "検索ワード(例:ステーキ)"%>
    <%= f.text_field :area, placeholder:"検索地域(例:銀座)"%>
    <%= f.submit "検索"%>
  <% end %>
</div>

<% if @response_data.include?("gnavi") %>
  <script>
    alert('ヒットする情報はありませんでした。')
  </script>
<% else%>
  <div class="row">
    <% @response_data["response"].each.with_index do |(k,v),i| %>
      <% if k == "#{i - 3}" %>
        <% review_data = v["photo"]%>
        <div class="card col-md-4 mb-3 p-0">
          <div class="card-header">
            <a href=<%= review_data["shop_url"]%>><%= review_data["shop_name"]%></a>
          </div>
          <div class="card-body">
            <p>エリア：<%= review_data["prefname"].slice(7...11) %>,<%= review_data["areaname_s"] %></p>
            <p>メニュー名：<%= review_data["menu_name"]%></p>
            <img src="<%= review_data["image_url"]["url_320"]%>" alt="画像" width="300" height="200">
            <p class="mt-3"><%= review_data["comment"]%></p>
            <%= review_data["update_date"]%>
          </div>
          <%= render "favorites/favorites_button", review: @review, review_data: review_data%>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>アカウント作成</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="d-flex align-items-center justify-content-center"><%= current_user.name%>さんのお気に入り一覧</h1>

<div class="row">
  <% @likes.each do |like| %>
    <div class="card col-md-4 mb-3 p-0">
      <div class="card-header">
        <a href=<%= like.shop_url%>><%= like.shop_name%></a>
      </div>
      <div class="card-body">
        <p>メニュー名：<%= like.menu_name%></p>
        <img src="<%= like.image_url%>" alt="投稿画像" width="300" height="200">
        <p class="mt-3"><%= like.comment%></p>
        <%= like.update_date%>
      </div>
      <%= render "favorites/favorites_button", review: @review, review_data: like%>
    </div>
  <% end %>
</div>